version: '3'

services:

  hydra:
    image: oryd/hydra:v1.11.7
    container_name: hydra
    ports:
      - 4444:4444
      - 4445:4445
      - 9020:9020
    command: serve all --dangerous-force-http
    environment:
      - DSN=memory
      - URLS_SELF_ISSUER=http://127.0.0.1:4444/
      - SERVE_PUBLIC_PORT=4444
      - SERVE_ADMIN_PORT=4445
      - STRATEGIES_ACCESS_TOKEN=jwt
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public
